name: Sync Debugging Visualization Tool from Repo autonomy-planning-devel
on:
  # 매 시간마다 체크
  schedule:
    - cron: '0 * * * *'  # 수정된 cron 표현식
  # 수동으로도 실행 가능
  workflow_dispatch:
    inputs:
      reason:
        description: '설-명'
        required: false
        default: 'PnC Vis Tool 파일 수동 동기화'
      
jobs:
  sync:
    runs-on: ubuntu-latest
    strategy:
       matrix:
        branch: [master]
    steps:
      - name: Checkout Current Repository (autonomy-common-api)
        uses: actions/checkout@v4
        with:
          ref: ${{ matrix.branch }}
          
      - name: Checkout Target Repository (autonomy-planning-devel)
        uses: actions/checkout@v4
        with:
          repository: zed654/pytorch
          path: temp-planning
          ref: ${{ matrix.branch }}
          
      - name: Copy files
        run: |
          mkdir -p common_package/data/rviz
          cp temp-planning/test/test.cpp common_package/data/rviz/

      - name: Update Timestamp
        run: |
          # 현재 날짜와 시간을 특정 파일에 기록
          date "+%Y-%m-%d %H:%M:%S" > timestamp.txt
          
      - name: Check for Changes and Push
        run: |
          if [[ -n "$(git status -s)" ]]; then
            git config --local user.email "ch7170p@naver.com"
            git config --local user.name "Changhyeon Park"
            git add .
            git commit -m "Sync: Update files from autonomy-planning-devel [world_coordinate_LDM.rviz]"
            git push
          else
            echo "No changes detected"
          fi
